Repository wecode-bootcamp-korea/27-1st-ZARANARA-frontend, pull requests merged in 2021-12, with the labels that each got.

#5 [27기 정소영] 공통 icon 파일위치 이동
  public/images/icon/arrow_left.svg
  public/images/icon/arrow_right.svg
  public/images/icon/cart.svg
  public/images/icon/hamberger.svg
  public/images/icon/logo1.svg
  public/images/icon/logo2.svg
  public/images/icon/profile.svg
  src/assets/icon/android.svg
  src/assets/icon/apple.svg
  src/assets/icon/arrow_left.svg
  src/assets/icon/arrow_right.svg
  src/assets/icon/cart.svg
  src/assets/icon/facebook.svg
  src/assets/icon/hamberger.svg
  src/assets/icon/instagram.svg
  src/assets/icon/kakao.svg
  src/assets/icon/logo1.svg
  src/assets/icon/logo2.svg
  src/assets/icon/pinterest.svg
  src/assets/icon/profile.svg
  src/assets/icon/spotify.svg
  src/assets/icon/twitter.svg
  src/assets/icon/youtube.svg
Labels: Status: 리뷰 요청

#4 [27기 양주영]nav 레이아웃 구현
  public/images/icon/android.svg
  public/images/icon/apple.svg
  public/images/icon/arrow_left.svg
  public/images/icon/arrow_right.svg
  public/images/icon/cart.svg
  public/images/icon/facebook.svg
  public/images/icon/hamberger.svg
  public/images/icon/instagram.svg
  public/images/icon/kakao.svg
  public/images/icon/logo1.svg
  public/images/icon/logo2.svg
  public/images/icon/pinterest.svg
  public/images/icon/profile.svg
  public/images/icon/spotify.svg
  public/images/icon/twitter.svg
  public/images/icon/youtube.svg
  public/images/nav/hamburgerMenu.png
  public/images/nav/user.png
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavData.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#1 [27기 양주영] footer 레이아웃 구현
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
Labels: Status: 리뷰 요청

#6 [27기 정소영]메인페이지 슬라이드 구현
  public/data/sliderMockData.json
  public/images/icon/android.svg
  public/images/icon/apple.svg
  public/images/icon/arrow_left.svg
  public/images/icon/arrow_right.svg
  public/images/icon/cart.svg
  public/images/icon/facebook.svg
  public/images/icon/hamberger.svg
  public/images/icon/instagram.svg
  public/images/icon/kakao.svg
  public/images/icon/logo1.svg
  public/images/icon/logo2.svg
  public/images/icon/pinterest.svg
  public/images/icon/profile.svg
  public/images/icon/spotify.svg
  public/images/icon/twitter.svg
  public/images/icon/youtube.svg
  public/images/img.md
  public/images/main/slider_image_cookieTool.jpg
  public/images/main/slider_image_lightball.jpg
  public/images/main/slider_image_treeToy.jpg
  src/assets/icon/android.svg
  src/assets/icon/apple.svg
  src/assets/icon/arrow_left.svg
  src/assets/icon/arrow_right.svg
  src/assets/icon/cart.svg
  src/assets/icon/facebook.svg
  src/assets/icon/hamberger.svg
  src/assets/icon/heart-active.svg
  src/assets/icon/heart.svg
  src/assets/icon/instagram.svg
  src/assets/icon/kakao.svg
  src/assets/icon/logo1.svg
  src/assets/icon/logo2.svg
  src/assets/icon/minus.svg
  src/assets/icon/pinterest.svg
  src/assets/icon/plus copy.svg
  src/assets/icon/plus.svg
  src/assets/icon/profile.svg
  src/assets/icon/spotify.svg
  src/assets/icon/twitter.svg
  src/assets/icon/youtube.svg
  src/components/Slider/Arrows/Arrows.js
  src/components/Slider/Arrows/Arrows.scss
  src/components/Slider/Dots/Dots.js
  src/components/Slider/Dots/Dots.scss
  src/components/Slider/Slider.js
  src/components/Slider/Slider.scss
  src/components/Slider/SliderContent/SliderContent.js
  src/components/Slider/SliderContent/SliderContent.scss
  src/config.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#9 [27기 김예슬] Button Component 생성
  src/components/Button/Button.js
  src/components/Button/Button.scss
Labels: Status: 수정 요청

#11 [27기 정소영] 장바구니 페이지 merge confilct 해결
  package-lock.json
  package.json
  public/data/cartMockData.json
  public/images/cart/cart_item_cup.png
  public/images/cart/cart_item_table-candle.png
  public/images/cart/cart_item_tree-ball.png
  public/images/cart/cart_item_tree-star.png
  src/Router.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartItem/CartItem.js
  src/pages/Cart/CartItem/CartItem.scss
  src/pages/Cart/CartItems/CartItems.js
  src/pages/Cart/CartItems/CartItems.scss
  src/pages/Cart/CartList/CartList.js
  src/pages/Cart/CartList/CartList.scss
  src/pages/Cart/LaterShop/LaterShop.js
  src/pages/Cart/LaterShop/LaterShop.scss
  src/pages/Cart/Price/Price.js
  src/pages/Cart/Price/Price.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#13 [27기 정소영] Footer 컴포넌트 레이아웃 수정
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#12 [27기 정소영] Nav 컴포넌트 레이아웃 수정 + merge confilct 해결
  src/Router.js
  src/assets/logo-white.svg
  src/assets/logo.svg
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Slider/Slider.js
  src/pages/Search/Search.js
  src/pages/Search/Search.scss
  src/styles/common.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#14 [27기 김예슬] 제품 리스트 페이지
  package-lock.json
  public/data/productListData.json
  public/images/listpage/velvet.jpg
  src/Router.js
  src/components/Nav/Nav.js
  src/index.js
  src/pages/JoinModal/JoinModal.js
  src/pages/JoinModal/JoinModal.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/LoginModal/LoginModal.js
  src/pages/LoginModal/LoginModal.scss
  src/pages/LoginModal/UserImformation.js
  src/pages/LoginModal/Userinput.js
  src/pages/LoginModal/Userinput.scss
  src/pages/Product_list/FilterAside/FilterAside.js
  src/pages/Product_list/FilterAside/FilterAside.scss
  src/pages/Product_list/Product/Product.js
  src/pages/Product_list/Product/Product.scss
  src/pages/Product_list/ProductItems/ProductItems.js
  src/pages/Product_list/ProductItems/ProductItems.scss
  src/pages/Product_list/productList/ProductList.js
  src/pages/Product_list/productList/ProductList.scss
Labels: Status: 리뷰 요청

#10 [27기 양주영] 디테일 페이지 수정 완료
  public/data/mockDataDetail.json
  public/images/icon/android.svg
  public/images/icon/apple.svg
  public/images/icon/arrow_left.svg
  public/images/icon/arrow_right.svg
  public/images/icon/cart.svg
  public/images/icon/facebook.svg
  public/images/icon/instagram.svg
  public/images/icon/kakao.svg
  public/images/icon/logo1.svg
  public/images/icon/logo2.svg
  public/images/icon/pinterest.svg
  public/images/icon/profile.svg
  public/images/icon/spotify.svg
  public/images/icon/twitter.svg
  public/images/icon/youtube.svg
  src/Router.js
  src/components/Button/Button.scss
  src/components/DetailModal/DetailModal.js
  src/components/DetailModal/DetailModal.scss
  src/components/ProductInfoTable/ProductInfoTable.js
  src/components/ProductInfoTable/ProductInfoTable.scss
  src/components/ProductInfoTable/ProductInfoValue/ProductInfoValue.js
  src/components/ProductInfoTable/ProductInfoValue/ProductInfoValue.scss
  src/components/ProductRelatedItems/ProductRelatedItems.js
  src/components/ProductRelatedItems/ProductRelatedItems.scss
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/DetailContent.js
  src/pages/Gift/Gift.js
  src/pages/Gift/Gift.scss
Labels: Status: 리뷰 요청

#15 [27기 정소영] Nav 컴포넌트 스크롤 기능 구현 + merge confilt 해결
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/useScroll.js
Labels: Status: 리뷰 요청

#16 [27기 정소영] 제품 리스트 페이지 레이아웃 수정
  src/Router.js
  src/config.js
  src/pages/Product_list/FilterAside/FilterAside.js
  src/pages/Product_list/FilterAside/FilterAside.scss
  src/pages/Product_list/Product/Product.js
  src/pages/Product_list/Product/Product.scss
  src/pages/Product_list/ProductItems/ProductItems.js
  src/pages/Product_list/ProductItems/ProductItems.scss
  src/pages/Product_list/productList/ProductList.js
  src/pages/Product_list/productList/ProductList.scss
Labels: Status: Accepted

#3 [27기 김예슬] 로그인&회원가입 레이아웃 구현 + confilct 해결
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Gift/Gift.js
  src/pages/JoinModal/JoinModal.js
  src/pages/JoinModal/JoinModal.scss
  src/pages/Login/Login.js
  src/pages/LoginModal/Button.js
  src/pages/LoginModal/LoginModal.js
  src/pages/LoginModal/LoginModal.scss
  src/pages/LoginModal/Userinput.js
  src/pages/LoginModal/Userinput.scss
Labels: Status: 리뷰 요청

#17 [27기 정소영] 장바구니 페이지 백엔드 데이터 통신 및 key 값 수정 + 장바구니 호버 기능 추가
  public/data/cartMockData.json
  src/components/Cart/CartItem/CartItem.js
  src/components/Cart/CartItem/CartItem.scss
  src/components/Cart/CartItem/NavCartItem.js
  src/components/Cart/CartItem/NavCartItem.scss
  src/components/Cart/CartItems/CartItems.js
  src/components/Cart/CartItems/CartItems.scss
  src/components/Cart/CartList/CartList.js
  src/components/Cart/CartList/CartList.scss
  src/components/Cart/LaterShop/LaterShop.js
  src/components/Cart/LaterShop/LaterShop.scss
  src/components/Cart/Price/Price.js
  src/components/Cart/Price/Price.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/LaterShop/LaterShop.js
Labels: Status: 리뷰 요청
